### ISSUE TITLE
Next Level To-Do

### ISSUE THREAD

**Issue by sbernstein94** [sbernstein94/sheepscot-notification#2]
- [ ] Allow user to chose whether they want to reference Portland or Wiscasset tide charts
- [ ] Allow user to specify custom time after high tide 
- [ ] Add other tidal playspots once running. Blue Hill, St John, etc.
